apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chroma.name }}
  labels:
    app: {{ .Values.chroma.name }}
spec:
  selector:
    app: {{ .Values.chroma.name }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
